version: '3.8'

services:
  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile.ws
    container_name: party-websocket
    restart: always
    ports:
      - "3001:3001"
    environment:
      WS_PORT: 3001
      NODE_ENV: production

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: party-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env

